USE NESTED;
DROP VIEW IF EXISTS V_GET_USER;
CREATE VIEW V_GET_USER AS
SELECT
        U.UUID AS UUID,
        U.U_EMAIL AS EMAIL,
        U.U_PWD AS PWD,
        U.U_PHONE AS PHONE,
        CONCAT(U.U_F_NAME, ' ', U.U_L_NAME) AS 'NAME',
        U.CURP AS CURP,
        U.U_IMG AS IMG,
        A.A_AVENUE AS AVENUE,
        A.A_EXT_NUMBER AS EXT_NUMBER,
        A.A_INT_NUMBER AS INT_NUMBER,
        A.A_CITY AS CITY,
        A.A_STATE AS 'STATE',
        A.A_COUNTRY AS CONTRY,
        UT.U_TYPE_DESC AS 'TYPE'
    FROM 
        USERS AS U
    JOIN
        USER_TYPES AS UT
            ON UT.U_TYPE = U.U_TYPE
    JOIN
        ADDRESSES AS A
            ON A.A_UID = U.U_ADDRESS

SELECT * FROM NESTED.V_GET_USER WHERE EMAIL = 'KEED@GMAIL.COM' AND PWD = '123';